apiVersion: v2
name: github-backup-utils
description: GitHub Enterprise Backup Utilities
keywords:
- github-enterprise-server
- github-enterprise
- backup-utils
- disaster-recovery
type: application
<<<<<<< Updated upstream
version: 0.1.0
appVersion: 3.9.1
=======
version: 0.2.0
appVersion: 3.10.0
>>>>>>> Stashed changes
home: https://github.com/github/backup-utils
sources:
- https://github.com/github/backup-utils
maintainers:
- name: younsl
  email: cysl@kakao.com
  url: https://github.com/younsl
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/younsl/github-backup-utils