# Global labels for all resources
labels: {}
  # app: github-backup-utils
  # environment: prd

backupUtils:
  enabled: true

  # Cron expression for scheduled backups
  # backup-utils team recommends hourly backups at the least
  # ref: https://github.com/github/backup-utils/blob/master/docs/scheduling-backups.md#scheduling-backups
  schedule: "0 * * * *"

  # known_hosts data
  # "[github.example.com]:122 ecdsa-sha2-nistp256 AAA............I="
  #   ------------------      ------------------- -----------------
  #    GHES Hostname or          Host key type     Host public key
  #    IP Address
  knownHosts: "[github.example.com]:122 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPHiBn7ko/8AE2Mwa01HB3Ef+ZZ92fg2PDjM/180eAXCYo0II9JeUVJO1hFXk6W10WfsHPabQgx8zV0ddaL9RzI="

  backupConfig:
    # IP address or hostname of Github Enterprise server
    githubEnterpriseHostname: "github.example.com"

    # Maximum number of snapshots to keep
    snapshotRententionNumber: 72

    # Absolute path where detailed backup logs are stored
    verboseLogFile: "/data/backup-verbose.log"

    # Extra SSH options for backup-utils pod to connect to GHE instances
    # We usually recommend not to modify the default value for stability reasons
    extraCommandOptions: "-i /ghe-ssh/id_ed25519 -o UserKnownHostsFile=/ghe-ssh/known_hosts"

  image:
    repository: 111122223333.dkr.ecr.ap-northeast-2.amazonaws.com/<YOUR_ECR_REPOSITRY_NAME>
    tag: v3.9.1
    pullPolicy: IfNotPresent

  persistentVolume:
    # If EKS cluster does not have the EBS CSI Driver installed, use gp2 instead of gp3.
    # Check whether gp3 is installed by using `kubectl get storageclass -A` command.
    storageClass: gp3
    # storageClass: gp2

    # Volume size where snapshot backups are stored
    # volume size vary based on current Git repository disk usage and growth patterns of your GitHub appliance
    # at least 5x the amount of storage allocated to the primary GitHub appliance for historical snapshots and growth over time
    # ref: https://github.com/github/backup-utils/blob/master/docs/requirements.md#storage-requirements
    size: 1500Gi

    accessModes:
      - ReadWriteOnce
      # - ReadOnlyMany
      # - ReadWriteMany
      # - ReadWriteOncePod

    # Extra labels for persistent volume claim
    labels: {}
      # app: github-backup-utils
      # environment: prd

  # Resource requests and limits for github-backup-utils container
  # ref: https://github.com/github/backup-utils/blob/master/docs/requirements.md#backup-host-requirements
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
